version: '3.8'

services:
  # Backend Service
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server 
      - /app/server/node_modules 
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/content_review_db
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mongo
      - ai-service
      - redis 

  # Frontend Service
  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client/src:/app/client/src 
    depends_on:
      - server

  # Database Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ai-service:
    build: ./ai-service
    ports:
      # Exposing port 8000 for local debugging if needed
      - "8000:8000"
    volumes:
      - ./ai-service:/app/ai-service
    

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  worker:
    build: ./server 
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    env_file:
      - ./server/.env
    
    command: npm run start:worker
    depends_on:
      - redis
      - mongo

volumes:
  mongo-data: